title: IB Economics Guide
description: Resources for IBDP Economic course
theme: just-the-docs

url: https://jeremyzxi.github.io/ib-econ-study-group

aux_links:
  Template Repository: https://github.com/JeremyZXi/IB-economic-study-group

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

  # Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: 'Your Footer'