title: IB Economics Guide
description: Resources for IBDP Economic course
theme: just-the-docs

url: https://jeremyzxi.github.io/ib-econ-study-group

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
